### ISSUE TITLE
투두 입력란의 체크표시 아이콘

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#100]
디자인 알못이 순전히 의미론적으로만 바라봤을 때의 의견입니다🙇‍♀️
![image](https://user-images.githubusercontent.com/66259746/187484333-236d7994-3c78-45c5-9a1e-309bdf5f87de.png)

저희 체크표시가 입력 아이콘의 모습인데 보통 체크표시는 완료 표시로 많이 쓰이잖아요? 이게 UX적으로 헷갈리지는 않을까요? 위치상으로는 문제가 없지만 핀이나 종이비행기? 같은 아이콘도 한번 검토해보면 좋지않을까 하는 생각이 들었습니다.

**Comment by jayjeong8** [comment]
입력아이콘을 +로 , 투두항목의 완료 표시를 v(체크아이콘)으로 변경하려고 합니다!

**Comment by jayjeong8** [comment]
![image](https://user-images.githubusercontent.com/82160479/188653074-5bc254c4-1f9d-4e31-b15c-70a2e0fc3298.png)
두둥
