### ISSUE TITLE
Print the Receipt 버튼을 어떻게 수정해야 UX적으로 더 개선할 수 있을까요?

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#101]
마지막 날 다른 스프린트 참가자들의 피드백을 받으며 생각보다 제법 많은 분들이 영수증 출력 버튼을 쉽게 찾지 못하는 모습이 있었습니다.
투두 입력창에 상대적으로 기능 및 요소들이 몰려있어, 하단에 위치한 출력 버튼 보다 가까이에 있는 영수증 모양 버튼(마이페이지 이동 버튼)에 더 먼저 눈이 가서 헤메게 되는 듯 합니다.
어떻게 수정해야 좋을까요?

**Comment by parkjooyoung0608** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/72453080/187496461-dab8d90b-0dd5-4d94-bd47-5f8d10c3006f.png">
스크롤 다운 애니메이션 처럼 클릭해달라는 의미의 아이콘을 넣는건 어떨까요???

**Comment by IGhost-P** [comment]
저는 개인적인 생각으로는 '평범하지 않은 버튼' 이였기 때문에 그런게 아닐까 생각합니다.
보통 버튼이라 하면 네모난 버튼을 생각하지 뾰족한 버튼이라 생각하진 않으니깐요... 하지만 저희 디자인 컨셉에서 중요한 부분이라서 해당 디자인을 변경하고 싶지는 않고, 문구를 변경하거나. 애니메이션을 주는 형태로 제공하면 좋지 않을까..? 라 생각합니다!

**Comment by mdgarden** [comment]
저도 레몬 아이디어랑 비슷한 생각이에요
문구가 영어로 되어있는것도 있고 그래서 화살표를 넣어서 "동작"을 하는 버튼이라는 것을 좀 더 명확하게 보여줄 수 있으면 좋을 것 같아요

예)
`Print the Receipt →`

**Comment by jayjeong8** [comment]
지금 형태를 유지한 상태로 버튼 그림자 및 양각을 살짝 넣어서 먼저 테스트해보고 
이후에도 개선되지 않으면 좀 더 명확하게 버튼임을 나타낼 수 있는 조치를 취하겠습니다!

**Comment by jayjeong8** [comment]
![스크린샷 2022-09-06 21-51-57](https://user-images.githubusercontent.com/82160479/188642049-33636a17-244e-4a97-8de9-16b04af17261.png)
![스크린샷 2022-09-06 21-52-09](https://user-images.githubusercontent.com/82160479/188642066-ca79af58-7672-4058-9329-788b8cd07312.png)
![스크린샷 2022-09-06 21-52-36](https://user-images.githubusercontent.com/82160479/188642076-e59d4598-441e-4f9d-8190-5819e385d0d6.png)
![스크린샷 2022-09-06 22-01-15](https://user-images.githubusercontent.com/82160479/188642083-5410c239-b03f-4217-84f4-e1faa41ab902.png)
![스크린샷 2022-09-06 22-01-34](https://user-images.githubusercontent.com/82160479/188642089-8fcb5218-42ef-40dc-8a39-97e9a29f22b4.png)

**Comment by jayjeong8** [comment]
화살표를 넣어 테스트해봤는데 이 앱의 감성과는 어울리지 않는다는 생각이 들었습니다.. 개인적으로는 4,5번처럼 버튼과 버튼 배경에 음영을 넣어서 (깃허브가 다크모드가 아니면 잘 안보일 수 있습니다!) 진행하고 5번처럼 글씨크기를 약간 키운다던지.. 하는 방법이 좋을 것 같습니다.
