### ISSUE TITLE
SNS 로그인 구현 (UI)

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#105]
## 요약
카카오 말고 다른 소셜 로그인 구현에 대해 화면 레이아웃을 확정해야합니다.

## 내용
- [ ] 화면 레이아웃 확정(카카오 로그인 페이지에 넣을건지? 별도의 화면을 넣을건지?)
- [ ] 어느 소셜 로그인을 가능하게 할지
- [ ] 로그인 버튼 UI 조정이 가능한지, 조정할 수 있다면 어떻게 바꿀건지

## 참고
확인은 해야겠지만 보통 다음과 같은 느낌의 버튼이 제공되고 수정할..수있을겁니다(아마도)
![image](https://user-images.githubusercontent.com/66259746/187606276-af8bed9c-4363-4c37-ba76-67157020b77b.png)

어느 소셜 로그인 버튼만 넣을지는 우리가 선택할 수 있습니다.

**Comment by jayjeong8** [comment]
어느 소셜로그인을 넣을지 논의 후 정해지면 개수에 따라서 페이지 구성해보겠습니다~!

**Comment by IGhost-P** [comment]
앱으로 구현할땐 꼭!! 애플 로그인이 필요합니다!!

**Comment by jayjeong8** [comment]
임의로 버튼을 넣어서 필요한 로그인을 구현해놓으면 그거에 따라 유아이를 입히는 방법도 있습니다!

**Comment by mdgarden** [comment]
3차 스프린트로 일정 수정하겠습니다. 
수정 사유는 #103 과 같습니다.

**Comment by mdgarden** [comment]
추후 다시 필요해질때 재오픈하겠습니다.
