### ISSUE TITLE
타이머가 초로 카운트 되는 현상

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#107]
타이머가 초로 내려가요

**Comment by mdgarden** [comment]
#97 이랑 비슷한것 같아요~~

**Comment by IGhost-P** [comment]
# 이슈 해결 결과
- constants에 있는 delay time을 원래대로 60000으로 바꿨습니다!
# 이슈 발생 원인
- test용으로 600ms로 바꿨는데, 다시 바꾸지 못했음

# 작업하는 브랜치
/feature/DanErrorCheck
