### ISSUE TITLE
리펙토링을 해야하지 않을까 싶어요..!

### ISSUE THREAD

**Issue by IGhost-P** [EasyAndBeauty/DailyReceipt-FE-WEB#110]
# 내용
1. 현재 atomic design과 일반 컴포넌트 방식이 섞여 있어서 하나로 통일하는게 좋을것 같아요
2. atomic design으로 한다면 좀 더 개발자 친화적이게  
![image](https://user-images.githubusercontent.com/79236624/187842378-acb09ecf-7ce9-4925-a85b-6d643dfb81c9.png)
폴더명과 동일한 jsx => 해당 폴더에서 js에서 export를 함 => components index.js에서 모아서 사용
으로 하면 나중에 유지보수 할때 더 편할것 같아요!
3. JSDoc 사용하기 , 타입스크립트를 사용하지 않는 지금, 나중에 유지보수나, 해당 컴포넌트 또는 함수를 사용할때 실수 하기가 쉽기때문에 JSDoc을 써보는건 어떨까요?

**Comment by mdgarden** [comment]
개인적으로는 스타일 컴포넨트 자체를 이번에 처음써보고 JSDoc이라는 것도 처음 들어봐서 의견 내기가 어렵네요(아는게 없네요..🥲)
1,2,3번 전부 판단은 댄과 다른분들께 맡기겠습니다. 
추가적으로 리팩토링을 한다면 hook이나 html/css가 아닌 부분에서 도와드릴 수 있을 것 같아요.

**Comment by mdgarden** [comment]
추가 의견)
최종적으로는 eslint에서 나오는 에러도 전부 해결했으면 좋겠습니다.
<img width="817" alt="image" src="https://user-images.githubusercontent.com/66259746/188137557-236c902c-a377-4de0-96f2-301cba01c081.png">
