### ISSUE TITLE
[issue] 인스타그램 API 신청 및 발급

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#122]
## 요약
인스타그램 API를 이용할 수 있도록 신청합니다.  가급적이면 빠른 시일내에 신청해서 개발일정에 차질이 없도록합니다.

**Comment by IGhost-P** [comment]
인스타그램 API를 web에서 사용할수 없는 이슈로 해당 이슈는 close하겠습니다!
