### ISSUE TITLE
[issue] 카카오에서 가져올 정보

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#125]
## 요약
카카오에서 어떤 정보를 가져올지 이야기해보고 싶습니다.

## 상세
스프린트 맨처음 와이어프레임을 짤 때 카카오에서 가져온 사용자 프로필 사진도 있었던 것 같습니다.
닉네임은 웹에서 설정한다해도, 프로필 사진도 필요할까요?
만약 필요하다면 사용자가 개별적으로 올리게하나요, 아니면 카카오에서 가져와야하나요?
카카오에서 가져와야할 경우 백엔드에도 API가 추가되어야하고 UI/UX도 정해야하기 때문에 빠르게 결정해야할 것 같습니다.

**Comment by java-saeng** [comment]
저는 유저를 식별할 수 있는 카카오 ID만 가져와도 될 거라고 생각해요

우리는 커뮤니티 사이트가 아닌 TODO List를 통해 "영수증"을 공유하는 애플리케이션이므로 굳이 프로필 사진이 필요할까 싶습니다 ~
