### ISSUE TITLE
[feature] API + 카카오 토큰 확인

### ISSUE THREAD

**Issue by IGhost-P** [EasyAndBeauty/DailyReceipt-FE-WEB#126]
## 요약
백에서 만들어준 API와 카카오 로그인 기능을 연결합니다. 추가로 리펙토링이 필요하면 리펙토링을 진행하겠습니다.

### 게스트 모드 일때
- [x] 게스트 상태에서 로그인이 가능
- [x] 게스트 상태일때 로그인이 필요한 페이지는 루트페이지로 리다이렉트

### 로그인 상태일때
- [x] 토큰을 이용해서 사용자의 정보를 확임
- [x] API 호출이 정상적으로 DB에 반영
- [ ] 게스트 모드 -> 로그인 모드로 전환될때 localStorage의 todolist가 반영

## 테스트 케이스
- [ ] API GET 요청을 보낼때, 해당 날의 todo가 온다 (날짜가 변경될때마다 get요청이 실행됨)
- [ ] API POST 요청을 보낼때, 해당 todo가 DB에 반영이 된다, 이후 get 요청이 정상적으로 실행되어 보여진다
- [ ] API PUT 요청을 보낼때, 해당 todo가 DB에 수정, 반영된다, 이후 get 요청이 정상적으로 실행되어 보여진다
- [ ] API DELETE 요청을 보낼떄, 해당 todo가 삭제된다, 이후 get 요청이 정상적으로 실행되어 보여진다
- [ ] 로그인시, 사용자의 정보를 받아온다
- [ ] 로그인시, localStorage에 사용자의 정보가 저장인된다
- [ ] 로그인시, localStorge에 있던 todolist가 DB에 반영된다 =>
    - bug가 발생할수 있는 상황 : 사용자가 오늘 DB에 저장을 한뒤 => 로그아웃을하고, todo를 추가 작성한뒤 => 다시 로그인 (todo가 겹치게 됨)  
- [ ] 로그인시, 전역상태관리에서 login이 활성화가 된다
- [ ] 로그인시, 로그인전에는 리다이렉트되었던 페이지에 접근이 가능하다

**Comment by mdgarden** [comment]
아이고 댄 저 이걸 이제 봤네요
> 게스트 모드 -> 로그인 모드로 전환될때 localStorage의 todolist가 반영

그래서 저번에 말씀해주셨던거군요 ㅠㅠ
제가 그 때 대답해드리긴 했는데 다른 분들게도 공유하고 싶어서 댓글로 기록 남깁니다!

저희 처음 스프린트 때도 같은 얘기가 나왔었는데 
1. 로컬 스토리지와 백엔드 사이의 데이터 정합성 문제
2. 기획의 문제(로그아웃 할 때 로컬 스토리지는 삭제되어야하는가? 아닌가? 등의 유저 시나리오 자체의 부재)
3. 백엔드와도 의논이 필요한 문제

등등이 있어서, 당시 스프린트에서 구현하기에는 어려움이 많아 우선 게스트면 무조건 로컬 스토리지, 회원이면 무조건 백엔드 API 였던걸로 결론을 내렸었던 것 같아요. 혹시 그 때 제대로 전달을 못드렸었다면 죄송합니다. 그치만 장기적으로는 꼭 생각해봐야할 문제라고 생각해요!
