### ISSUE TITLE
[issue] 뽀모도로 타이머의 보기모드가 있으면 어떨까요?

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#127]
## 상세
뽀모도로 타이머의 원래 목적은 집중이잖아요?
그래서 다른 투두를 확인할 수 있는 간편모드(지금 구현되어있는 상태의 뽀모도로)와 화면 전체를 다 가리는 집중모드 뽀모도로 타이머 화면이 있으면 어떨까..하는 생각이 들어용
급한건 아니고 완전히 새로운 이슈라서 하게되더라도 3차 스프린트로 들어가게 될 것 같은데 여러분 생각은 어떠신가요?

**Comment by IGhost-P** [comment]
좋은 방법인것 같습니다! 저도 핸드폰으로 볼때 뽀모도로가 작아서 잘 안보이는 문제가 있었거든요..!

**Comment by mdgarden** [comment]
4차 스프린트 때 다시 얘기해보겠습니다 ~
