### ISSUE TITLE
[issue] 마이영수증 페이지 콘텐츠 구성에 대하여

### ISSUE THREAD

**Issue by jayjeong8** [EasyAndBeauty/DailyReceipt-FE-WEB#129]
## 요약
마이영수증 페이지 UI 시안을 작업하고 생각해보니 들어갈 콘텐츠가 없다라는 생각이 들었습니다!
개발자 정보나 무언가 넣고싶은게 있다면 미팅때 이야기 나눠보고 싶어요!!

**Comment by mdgarden** [comment]
#124 에도 적었는데 닉네임을 수정할 수 있는 버튼이나 뭔가의 UI가 있었으면 좋겠어요!

**Comment by mdgarden** [comment]
## 기능
- 닉네임 표시
- 영수증 개수 표시
- 가로 영수증 표시
- 로그아웃
- 비로그인시 리다이렉션
- 닉네임 수정

## 요소
- 개발자 정보
- 깃허브 링크
- 개인정보 취급 어쩌구
