### ISSUE TITLE
[feature]400,500번대 에러화면 만들기

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#134]
## 요약
API통신오류, 서버에러 등등을 위한 400번대, 500번대 에러 화면 만들기

## 완료조건
- [x] 404 에러화면 UI 만들기 (유저가 URL을 잘못입력했을 경우)
- [ ] 구현
- [x] 500번대 에러화면 UI  만들기 (서버에러, 프론트의 동작문제 등등이 발생했을 경우 리다이렉트 시켜주는 화면)
- [ ] 구현

## 테스트 케이스
추후 작업 담당자가 작성해주세요.

**Comment by IGhost-P** [comment]
폰트 weight가 변경 || 폰트 색깔이 회색검은색 느낌으로
