### ISSUE TITLE
[feature] 뽀모도로 미이용시 최소 시간 수정

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#167]
## 요약
뽀모도로를 한번도 실행안했을 경우, 영수증에 누적 시간을 0:00으로 변경합니다.

## 완료조건
- [x] 초기 시간을 0:00 으로 변경

## 테스트 케이스
- [x] 뽀모도로 타이머를 한번도 누르지 않고 영수증을 출력했을 경우, 시간이 0:00으로 표시된다.
- [x] 뽀모도로 타이머를 1분 미만으로 실행하고 영수증을 출력했을 경우, 시간이 0:00으로 표시된다.

**Comment by gygy7151** [comment]
처음엔 ReceiptTodo 컴포넌트에서 timer값이 1이 들어오면 무조건 0으로 초기화되도록 설정했으나,
실재로 1분이 누적되었는데도 0으로 카운트 되는 논리적 오류가 발생했습니다.
댄의 조언으로 ToDoInsert 컴포넌트의 onClickTodoItemCreateButton에서 todoItem 객체의 timer 초기 값을 1에서 0으로 바꿔주어서 이슈를 해결했습니다.

**Comment by IGhost-P** [comment]
고생했씁니다 블루~ 얼른 자요~

**Comment by gygy7151** [comment]
고맙습니당 댄도 언넝 과제 잘 마무리하시구 꿀잠 줌시길 ㅠㅠ바래요!!! @IGhost-P
