### ISSUE TITLE
[issue] : 영수증에서 시간 합이 문자열로 더해지는 문제

### ISSUE THREAD

**Issue by IGhost-P** [EasyAndBeauty/DailyReceipt-FE-WEB#179]
## 요약
영수증을 출력했을때 영수증의 합/ 총합이 문자열로 더해지는 문제가 있습니다.
아마 기존 api에서 timer가 숫자 => 문자열로 변경되면서 생기는문제 같은데, 이런경우를 예상해서 timer 부분 숫자를 Number()로 강제했어야했는데.. 죄송합니다
![my_receipt_2022-10-13](https://user-images.githubusercontent.com/79236624/195539089-3dd06b22-2e72-4141-9049-ca1191024517.png)

## 완료조건
- [ ] 영수증에서 뽀모도로 2회 이상 시간 누적시 숫자로 더해질것 (1+1 = 2 올바른, 1+1 =11이면 안됨)
- [ ] 영수증에서 총합이 숫자로 더해질것(위와 같음)

**Comment by mdgarden** [comment]
버그 발견 감사합니다!
사용에 있어 제법 크리티컬한 버그이므로 우선순위를 높여서 4차 스프린트 안에 해결하고 싶습니다.
