### ISSUE TITLE
[feature] 영수증 pin기능 추가

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#182]
## 요약 
영수증 pin 기능 추가

## 상세
- [x] pin 클릭시 fill 스타일 및 버튼이름명 pinned로 변경
- [ ] 영수증 작성 결과 화면에서 pin을 누르면 해당 영수증의 정보를 백엔드로 전송함
- [ ] 가로영수증 화면에서 pin된 영수증만 보여줌
- [ ] 영수증 작성 화면에서 pin을 해제할 수 있음
- [ ] 영수증 작성 화면에서 pin을 해제하면 해당 영수증의 pinned:false 정보를 백엔드로 전송함

**Comment by mdgarden** [comment]
급한대로 제가 우선 맡아서 진행해보겠습니다.

**Comment by jayjeong8** [comment]
pin 버튼 눌렀을 때의 프론트 동작은 적용되었습니다. atom/ReceiptPageBtns/PinBtn.jsx의 handlePin() 기능에 서버로 보내는 동작 추가가 필요합니다. 참고사항으로 기존 영수증페이지 버튼들이 ReceiptPage.jsx에 기능 포함해서 모여있었는데 각 버튼별로 atom/ReceiptPageBtns/ 경로에 리팩터링 하였습니다.

**Comment by mdgarden** [comment]
#195 로 인계합니다.
