### ISSUE TITLE
[issue] 영수증이 일정 길이가 넘어가면 하단부에 검은선 발생

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#196]

**Comment by mdgarden** [comment]
영수증 위에 선이 생기는게 아니라 1px정도 공간이 떠서 배경이 보이는듯합니다

**Comment by jayjeong8** [comment]
영수증 텍스쳐 이미지보다 영수증이 커질 경우 텍스쳐 이미지가 repeat 되면서 사이에 빈 틈이 생겨 백그라운드의 검정색이 나타나는 문제였습니다. 영수증 텍스쳐가 영수증 사이즈만큼 덮을 수 있게 하여 해결하였습니다.
