### ISSUE TITLE
[feature] UI 개선

### ISSUE THREAD

**Issue by jayjeong8** [EasyAndBeauty/DailyReceipt-FE-WEB#221]
## 요약
일부 UI의 레이아웃을 수정하고 더 나은 사용성을 위해 개선하려고 합니다. 

## 완료조건
- [x] 캘린더 UI가 왼쪽에 치우치지 않고 중앙에 오도록 수정
- [x] 투두 리스트의 목록이 많을 때 화면이 커도 아래쪽이 잘려서 스크롤로만 볼 수 있는 문제 수정 
- [x] 영수증 출력 페이지 pin 버튼을 누르면 나오는 모달 UI 수정 (버튼 간격 수정 및 텍스트 언어를 서비스에 맞게 수정)

**Comment by mdgarden** [comment]
높이가 작아질 경우 타이머의 레이아웃이 무너짐
<img width="492" alt="image" src="https://user-images.githubusercontent.com/66259746/209435937-ec32e708-b415-41ce-b4f7-ac57e3fa035b.png">
