### ISSUE TITLE
영수증 저장시 종이질감 텍스쳐가 반영되지 않음

### ISSUE THREAD

**Issue by jayjeong8** [EasyAndBeauty/DailyReceipt-FE-WEB#49]
저장 버튼을 누르면 html2canvas로 만든 영수증 컴포넌트를 canvas로 변환시켜서 다운받습니다.
깃허브 및 스택오버플로우에 나오는 options 적용 및 이미지 설정 변경을 시도했으나 성공하지 못했습니다.

**Comment by IGhost-P** [comment]
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/79236624/187821300-11cc9c9c-9348-40d9-98c3-4fbfc25c69cd.png">

# 이슈가 생긴 이유
1. 배경 이미지가 network로 부터 받아오는 이미지라서 canvas에서 캡쳐를 했을때는 아직 배경 이미지가 오기전
2. html2canvas는 비동기 함수이다. onClick시 async await로 호출을 해줘야함
3. receipt 내용과 이미지가 형제 노드 ==> opacity를 하면 뒷배경까지 먹음
![image](https://user-images.githubusercontent.com/79236624/187821734-b983ec6b-5d8a-4ee5-aa41-1daea82194d8.png)

# 이슈 처리하고 있는 브랜치
/feature/DanErrorCheck
