### ISSUE TITLE
투두 항목이 없어도 영수증 페이지로 넘어감

### ISSUE THREAD

**Issue by jayjeong8** [EasyAndBeauty/DailyReceipt-FE-WEB#52]
근데 나쁘지는 않은 것 같아요 수정 후순위라고 생각합니다!

**Comment by gygy7151** [comment]
영수증 출력페이지

**Comment by gygy7151** [comment]
if(!todos.length){ 투두의 갯수가 없을 경우 실행할 내용 } else {navigate~ 기존}으로 에러 핸들링
투두의 갯수가 없는 경우 alert창을 '항목이 없습니다'라는 내용을 담아 유저에게 알려줌
