### ISSUE TITLE
투두페이지 타이머 일시정지시 정지됨

### ISSUE THREAD

**Issue by jayjeong8** [EasyAndBeauty/DailyReceipt-FE-WEB#57]
한번 터치하면 일시정지 하기로 했는데 정지됩니다! 
근데 정지한 시간은 잘 기록되어서 저는 오히려 일시정지보다 좋은 것 같다는 생각이 듭니다.

**Comment by mdgarden** [comment]
정지한 시간은 기록된다는게 어떤뜻인가요?
뽀모도로 타이머에 기록되는 시간은 뽀모도로를 실시한 시간 + 정지한 시간의 합계 라는 말씀이신가요?

**Comment by jayjeong8** [comment]
2분 실행 후 정지하면 2분이 추가로 누적에 기록된다는 의미입니다~

**Comment by IGhost-P** [comment]
이 이슈는 그럼 해결 된걸까요?

**Comment by mdgarden** [comment]
정지로 사양변경하는 것에 팀원들이 동의했으므로 클로즈합니다.
