### ISSUE TITLE
투두 엔터로 입력을 가능하게 하기

### ISSUE THREAD

**Issue by jayjeong8** [EasyAndBeauty/DailyReceipt-FE-WEB#58]
저희가 그때 공통된 의견으로 엔터로 입력되는 걸 방지하자고 얘기했었는데,
테스트해보니 모바일과 pc 둘 다에서 사용자 경험이 저하된다고 생각해서 엔터 입력이 가능한 것으로 바꾸는게 좋을 것 같습니다.

**Comment by parkjooyoung0608** [comment]
https://github.com/EasyAndBeauty/DailyReceipt-FE-WEB/pull/65
해결했습니다!

**Comment by mdgarden** [comment]
현재 엔터가 다시 되고 있지않으므로 재오픈합니다.
