### ISSUE TITLE
투두를 길게 입력시

### ISSUE THREAD

**Issue by jayjeong8** [EasyAndBeauty/DailyReceipt-FE-WEB#59]
투두를 길게 입력하는 테스트를 해보았는데 너무 길어지니까 영수증이 예뻐보이지 않네요! 
또한 한글과 달리 영어로 길어지면 레이아웃을 뚫고 나가고 있습니다.

투두라는 특성상 항목이 그렇게 길어지지 않을 거라고 생각해서 20자 정도로 제한하면 좋을 것 같습니다.

**Comment by mdgarden** [comment]
20자 이상 넘어가면 영수증에서 ...로 줄이는건 어떨까요?
아니면 영수증이니까 영수증답게 표현하는 다른 문자나 문구도 있을 것 같아요 지금 생각나는건 없지만....😅
투두리스트 항목 자체는 유저가 어느정도 자유롭게 쓸 수 있는게 좋을 것 같다고 생각해요

**Comment by jayjeong8** [comment]
좋은 의견 감사합니다! 시간이 된다면 적용해보겠습니다!

**Comment by IGhost-P** [comment]
# 이슈 해결 결과
<img width="449" alt="image" src="https://user-images.githubusercontent.com/79236624/187824206-fd551565-81c8-43e2-aeb2-f515d5d219e9.png">
- makeEllipsis 라는 함수를 따로 만들어 지정한 글자 수를 넘으면 ... 처리로 변경했습니다 (현재 constants/index.js에서 20글자로 제한함)

# 이슈가 생긴이유
1. 글자가 길어도 width size가 정해져 있지 않기 때문

# 작업 브랜치
/feature/DanErrorCheck

**Comment by IGhost-P** [comment]
![image](https://user-images.githubusercontent.com/79236624/188252936-0eabf5d4-4cbf-47fe-bf0f-15db449e35bd.png)
css 작업으로 좀더 자연스럽게 했습니다!
