### ISSUE TITLE
뒤로가기버튼 

### ISSUE THREAD

**Issue by gygy7151** [EasyAndBeauty/DailyReceipt-FE-WEB#81]
마이페이지와 영수증 출력페이지에 뒤로가기 버튼이 필요할거 같아요!
그냥 크롭뒤로가기 버튼으로 페이지 이동하니깐 다소 불편한 감이 없잖아 있네여ㅎ

**Comment by jayjeong8** [comment]
영수증 출력페이지에는 뒤로가기 버튼이 있어요! 아마 큰사이즈 화면으로 보셨다면 UI가 깨져서 그런건데 이부분은 수정되었습니다!! 마이영수증 페이지는 제가 추가하기로 했어요 ㅎㅎ 감사합니다!!

**Comment by IGhost-P** [comment]
이슈 해결 된건가요?

**Comment by jayjeong8** [comment]
@IGhost-P 네 저희 1차 스프린트 마감날에 추가되었고 경로를 components에서 온걸로 수정했습니다!
