### ISSUE TITLE
투두 항목 완료 체크 후 버튼 색

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#82]
발생 환경
프로덕션 https://daily-receipt-fe-o9d9atxd7-ighost-p.vercel.app/

체크 전 
<img width="377" alt="image" src="https://user-images.githubusercontent.com/66259746/187137378-643ca435-039f-45a0-9343-c8e8ace70e0f.png">

체크 후
<img width="374" alt="image" src="https://user-images.githubusercontent.com/66259746/187137414-8a5513d2-a01c-47ae-8267-3b365989d61c.png">

선택 후 체크 버튼 배경이 회색이 되는데, 흰색으로 변경하면 더 이쁠 것 같아요!

**Comment by jayjeong8** [comment]
흑흑 초록색이 되는건데요,, 더 상큼하게 바꾸어볼게요!

**Comment by IGhost-P** [comment]
이슈 해결 된건가요? 초록색으로 보이기는 하는데..!

**Comment by mdgarden** [comment]
버튼의 배경색을 말하는거였어요..! 초록색은 문제 없는데 자세히 보시면 바탕색깔이 흰색이었다가 체크후에는 초록색 원 뒤로 배경이 회색으로 되어있어요.

#100 에서 원형 버튼을 체크표시로 바꾸기로 했으니 이 이슈는 클로즈 하겠습니다.
