### ISSUE TITLE
영수증 저장 방식 개선

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#86]
## 요약
이미지를 파일로 저장하기 때문에 저장 방식에 있어 UX 개선이 필요해보입니다.

## 내용
테스트 실시 환경 : 아이폰 8S

### 모바일 크롬
영수증 저장 버튼을 누르면 파일로 저장됩니다. 
![image](https://user-images.githubusercontent.com/66259746/187147171-c7e7f575-9971-4a80-95d6-20b528041ac7.png)

위 화면에서 `다음에서 열기`를 클릭하면 다음과 같은 옵션이 등장해서 카메라 앨범에 파일을 저장하기가 어렵습니다.
![image](https://user-images.githubusercontent.com/66259746/187147545-1ab41911-2221-44d7-8992-2b91260be1f9.png)

### 1. 이미지를 프론트에서 만들어서 모달이나 별도 페이지에서 제공
현재 컴포넌트로 영수증을 출력하고 있는데, 이미지 저장 버튼을 눌렀을 때 파일로 다운로드 하는게 아니라 프론트에서 이미지가 된 영수증을 모달로 띄워주는게 어떨까요? 그대로 캡쳐를 해도 좋고, 오래 눌러서 이미지 저장해도 좋을 것 같습니다.

### 2. 저장 버튼을 눌렀을 때 클립보드로 복사
편의적인 면에서는 이게 좋을 것 같긴하지만, 브라우저나 유저의 사용환경에 따라서 불가능한 경우도 있다고 합니다.

**Comment by IGhost-P** [comment]
# 개선 방안에 대한 의견
1. 이것도 금방 가능합니다
```jsx
  html2canvas(document.querySelector("#capture")).then(canvas => {
    // 모달에다가 바인딩
  });
```
하지만 모달의 UI가 정해지지 않아 이것을 먼저 진행해야 할 것 같습니다

2. react-copy-to-clipboard라이브러리를 사용하면 금방 가능합니다.

즉, 해당 이슈는 UX/UI를 결정하고 나서 해결하겠습니다

**Comment by jayjeong8** [comment]
![image](https://user-images.githubusercontent.com/82160479/188668143-72e4021a-ea31-4b16-81a5-a7f35ac438bf.png)
모달의 UI 시안을 만들어보았습니다.
저장버튼을 누르면 모달이 뜨게 할 것인지 등의 UX 적인 고민도 필요하겠네요!
