### ISSUE TITLE
영수증 저장 이름 개선

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#95]
매번 my_receipt으로 저장되는데 이름이 중복되니 my_receipt_날짜_닉네임 같은 이름으로 저장되면 좋을 것 같아요

**Comment by IGhost-P** [comment]
# 이슈 반영 결과
<img width="727" alt="image" src="https://user-images.githubusercontent.com/79236624/187837242-1d5be121-1dfe-4173-9e77-a3b88707209f.png">

- 이름이 있다면 이름을 보여주고 , 없다면 my_receipt
- 마지막에 날짜가 들어갑니다. 혹시 데이터를 못받을경우에는 빈값이 들어갑니다
