### ISSUE TITLE
Organization의 README파일 추가

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#96]
## 요약
처음 `EasyAndBeauty` 오거나이제이션에 들어왔을 때 리드미가 있었으면 좋겠어요!

## 내용
- [리드미 등록 방법](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile)
- 내용은 프론트 리드미 그대로 가져다써도 될 것 같습니다.

**Comment by IGhost-P** [comment]
리드미에 
dependancy와 contributer가 추가 되었음 좋을것 같아요!!
https://github.com/Team-Spino/YoGo 제 레포에 있는 내용입니다!

**Comment by gygy7151** [comment]
2022년 11월 29일까지 작업완료된 내용 반영해서 리드미 작성완료 했습니다.

**Comment by gygy7151** [comment]
- [x]  핀기능 설명 추가
- [x]  기술스택 설명 추가
- [x]  이슈해결방식 추가
- [x]  API설계서 링크 추가
- [x]  1~5차 스프린트 회고 및 진행과정 설명 추가
- [x] 기능 단위별 gif 파일 제작 및 업로드 완료
