### ISSUE TITLE
웹 페이지의 footer가 필요하지 않을까요?

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#97]
저작권 표시, 제작자 링크 표시 등등을 위한 푸터나 별도 영역이 필요할 것 같습니다.

**Comment by IGhost-P** [comment]
footer 부분에 버튼이 들어가다 보니 이부분은 고민을 좀 해보아할것 같아요! 오늘(9월1)일에 얘기를 나눠보면 좋을것 같습니다!

**Comment by jayjeong8** [comment]
footer에 들어갈 내용을 누가 맡아서 필요한 내용을 찾아 작성해주시면 좋을 것 같습니다!

**Comment by mdgarden** [comment]
저작권 표시
제작자 표시

지금은 이 정도가 아니려나 싶네요...?🤔
마이페이지에 들어가는 내용과 겹치는 듯하므로 우선 footer는 고려하지 않는 것으로 하겠습니다.
