### ISSUE TITLE
이슈/PR 템플릿화

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#99]
제가 쓰던 방식과 댄이 쓰던 방식의 템플릿에서 좋은점만 뽑아와서 우리 팀만의 템플릿을 새로 만들고 싶습니다.
[노션에 있는 이슈 템플릿](https://www.notion.so/Issues-Naming-Convention-a308fca400234f7dabd9384e58b74ca8)
개인적으로는 카테고리에 어떤 것을 쓰면 좋을지 한번 설명을 들어보고 싶어요!

**Comment by IGhost-P** [comment]
마당이 쓰는 방식이 어떤것인지 궁금해요!!

**Comment by mdgarden** [comment]
이슈 쓰는 방식은 크게 다를게 없습니다! 테스트케이스 추가하냐 안하냐의 차이인것 같아요 참고 : #98 
개인적으로는 브랜치 이름 작성이랑 커밋메세지에 이슈번호를 추가하는 방식에 대해서 얘기해보고 싶어요
예를 들어 커밋메세지에 feature : #99 이렇게 쓰면 자동으로 해당이슈에 커밋이 올라왔다고 연동되거든요!

**Comment by IGhost-P** [comment]
너무 좋은데요 마당?!?!? 역시 마당이야..!

**Comment by mdgarden** [comment]
## title

- [카테고리] 제목
- 카테고리 종류 
    - [issue] 버그, 질문 등
    - [feature] 구현할 기능
    - [backlog] 스프린트 목표

## 내용

- 간단한 설명
- 완료조건 명시
- 테스트케이스

**Comment by mdgarden** [comment]
이슈 템플릿 추가 완료했습니다. 새 이슈 작성하실 때 확인하실 수 있습니다.
https://github.com/EasyAndBeauty/DailyReceipt-FE-WEB/blob/develop/.github/ISSUE_TEMPLATE/------------.md
